name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if requirements.txt exists
        run: |
          if [ ! -f requirements.txt ]; then
            echo "requirements.txt not found!"
            exit 1
          fi

      - name: Install dependencies
        run: pip install -r requirements.txt
